// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.14.0
// source: proto/gamecoordinatorclient.proto

package gamecoordinatorclient

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryMatchDetailsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MatchId   uint64 `protobuf:"varint,1,opt,name=matchId,proto3" json:"matchId,omitempty"`
	OutcomeId uint64 `protobuf:"varint,2,opt,name=outcomeId,proto3" json:"outcomeId,omitempty"`
	Token     uint32 `protobuf:"varint,3,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *QueryMatchDetailsRequest) Reset() {
	*x = QueryMatchDetailsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_gamecoordinatorclient_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryMatchDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryMatchDetailsRequest) ProtoMessage() {}

func (x *QueryMatchDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gamecoordinatorclient_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryMatchDetailsRequest.ProtoReflect.Descriptor instead.
func (*QueryMatchDetailsRequest) Descriptor() ([]byte, []int) {
	return file_proto_gamecoordinatorclient_proto_rawDescGZIP(), []int{0}
}

func (x *QueryMatchDetailsRequest) GetMatchId() uint64 {
	if x != nil {
		return x.MatchId
	}
	return 0
}

func (x *QueryMatchDetailsRequest) GetOutcomeId() uint64 {
	if x != nil {
		return x.OutcomeId
	}
	return 0
}

func (x *QueryMatchDetailsRequest) GetToken() uint32 {
	if x != nil {
		return x.Token
	}
	return 0
}

type StatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_gamecoordinatorclient_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gamecoordinatorclient_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_gamecoordinatorclient_proto_rawDescGZIP(), []int{1}
}

func (x *StatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_gamecoordinatorclient_proto protoreflect.FileDescriptor

var file_proto_gamecoordinatorclient_proto_rawDesc = []byte{
	0x0a, 0x21, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x63, 0x6f, 0x6f, 0x72,
	0x64, 0x69, 0x6e, 0x61, 0x74, 0x6f, 0x72, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x15, 0x67, 0x61, 0x6d, 0x65, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e,
	0x61, 0x74, 0x6f, 0x72, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x22, 0x68, 0x0a, 0x18, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x49, 0x64,
	0x12, 0x1c, 0x0a, 0x09, 0x6f, 0x75, 0x74, 0x63, 0x6f, 0x6d, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x09, 0x6f, 0x75, 0x74, 0x63, 0x6f, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x2a, 0x0a, 0x0e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x32, 0x88, 0x01, 0x0a, 0x17, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x6d, 0x0a, 0x11,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x73, 0x12, 0x2f, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61,
	0x74, 0x6f, 0x72, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4d,
	0x61, 0x74, 0x63, 0x68, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x25, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e,
	0x61, 0x74, 0x6f, 0x72, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x1f, 0x5a, 0x1d, 0x2e,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x67, 0x61, 0x6d, 0x65, 0x63, 0x6f, 0x6f, 0x72, 0x64,
	0x69, 0x6e, 0x61, 0x74, 0x6f, 0x72, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_gamecoordinatorclient_proto_rawDescOnce sync.Once
	file_proto_gamecoordinatorclient_proto_rawDescData = file_proto_gamecoordinatorclient_proto_rawDesc
)

func file_proto_gamecoordinatorclient_proto_rawDescGZIP() []byte {
	file_proto_gamecoordinatorclient_proto_rawDescOnce.Do(func() {
		file_proto_gamecoordinatorclient_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_gamecoordinatorclient_proto_rawDescData)
	})
	return file_proto_gamecoordinatorclient_proto_rawDescData
}

var file_proto_gamecoordinatorclient_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_gamecoordinatorclient_proto_goTypes = []interface{}{
	(*QueryMatchDetailsRequest)(nil), // 0: gamecoordinatorclient.QueryMatchDetailsRequest
	(*StatusResponse)(nil),           // 1: gamecoordinatorclient.StatusResponse
}
var file_proto_gamecoordinatorclient_proto_depIdxs = []int32{
	0, // 0: gamecoordinatorclient.MatchDetailQueryService.QueryMatchDetails:input_type -> gamecoordinatorclient.QueryMatchDetailsRequest
	1, // 1: gamecoordinatorclient.MatchDetailQueryService.QueryMatchDetails:output_type -> gamecoordinatorclient.StatusResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_gamecoordinatorclient_proto_init() }
func file_proto_gamecoordinatorclient_proto_init() {
	if File_proto_gamecoordinatorclient_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_gamecoordinatorclient_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryMatchDetailsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_gamecoordinatorclient_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_gamecoordinatorclient_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_gamecoordinatorclient_proto_goTypes,
		DependencyIndexes: file_proto_gamecoordinatorclient_proto_depIdxs,
		MessageInfos:      file_proto_gamecoordinatorclient_proto_msgTypes,
	}.Build()
	File_proto_gamecoordinatorclient_proto = out.File
	file_proto_gamecoordinatorclient_proto_rawDesc = nil
	file_proto_gamecoordinatorclient_proto_goTypes = nil
	file_proto_gamecoordinatorclient_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// MatchDetailQueryServiceClient is the client API for MatchDetailQueryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MatchDetailQueryServiceClient interface {
	QueryMatchDetails(ctx context.Context, in *QueryMatchDetailsRequest, opts ...grpc.CallOption) (*StatusResponse, error)
}

type matchDetailQueryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMatchDetailQueryServiceClient(cc grpc.ClientConnInterface) MatchDetailQueryServiceClient {
	return &matchDetailQueryServiceClient{cc}
}

func (c *matchDetailQueryServiceClient) QueryMatchDetails(ctx context.Context, in *QueryMatchDetailsRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, "/gamecoordinatorclient.MatchDetailQueryService/QueryMatchDetails", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MatchDetailQueryServiceServer is the server API for MatchDetailQueryService service.
type MatchDetailQueryServiceServer interface {
	QueryMatchDetails(context.Context, *QueryMatchDetailsRequest) (*StatusResponse, error)
}

// UnimplementedMatchDetailQueryServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMatchDetailQueryServiceServer struct {
}

func (*UnimplementedMatchDetailQueryServiceServer) QueryMatchDetails(context.Context, *QueryMatchDetailsRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryMatchDetails not implemented")
}

func RegisterMatchDetailQueryServiceServer(s *grpc.Server, srv MatchDetailQueryServiceServer) {
	s.RegisterService(&_MatchDetailQueryService_serviceDesc, srv)
}

func _MatchDetailQueryService_QueryMatchDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryMatchDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchDetailQueryServiceServer).QueryMatchDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gamecoordinatorclient.MatchDetailQueryService/QueryMatchDetails",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchDetailQueryServiceServer).QueryMatchDetails(ctx, req.(*QueryMatchDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MatchDetailQueryService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gamecoordinatorclient.MatchDetailQueryService",
	HandlerType: (*MatchDetailQueryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryMatchDetails",
			Handler:    _MatchDetailQueryService_QueryMatchDetails_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/gamecoordinatorclient.proto",
}
