// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// DownloaderUseCase is an autogenerated mock type for the DownloaderUseCase type
type DownloaderUseCase struct {
	mock.Mock
}

// DownloadDemo provides a mock function with given fields: url, demoDir, lastModified
func (_m *DownloaderUseCase) DownloadDemo(url string, demoDir string, lastModified time.Time) error {
	ret := _m.Called(url, demoDir, lastModified)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, time.Time) error); ok {
		r0 = rf(url, demoDir, lastModified)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
