// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.1
// source: proto/valveapi.proto

package valveapiclient

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShareCode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Encoded   string `protobuf:"bytes,1,opt,name=encoded,proto3" json:"encoded,omitempty"`
	OutcomeId uint64 `protobuf:"varint,2,opt,name=outcomeId,proto3" json:"outcomeId,omitempty"`
	MatchId   uint64 `protobuf:"varint,3,opt,name=matchId,proto3" json:"matchId,omitempty"`
	Token     uint32 `protobuf:"varint,4,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *ShareCode) Reset() {
	*x = ShareCode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_valveapi_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShareCode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareCode) ProtoMessage() {}

func (x *ShareCode) ProtoReflect() protoreflect.Message {
	mi := &file_proto_valveapi_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareCode.ProtoReflect.Descriptor instead.
func (*ShareCode) Descriptor() ([]byte, []int) {
	return file_proto_valveapi_proto_rawDescGZIP(), []int{0}
}

func (x *ShareCode) GetEncoded() string {
	if x != nil {
		return x.Encoded
	}
	return ""
}

func (x *ShareCode) GetOutcomeId() uint64 {
	if x != nil {
		return x.OutcomeId
	}
	return 0
}

func (x *ShareCode) GetMatchId() uint64 {
	if x != nil {
		return x.MatchId
	}
	return 0
}

func (x *ShareCode) GetToken() uint32 {
	if x != nil {
		return x.Token
	}
	return 0
}

type ShareCodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SteamId              uint64 `protobuf:"varint,1,opt,name=steamId,proto3" json:"steamId,omitempty"`
	ApiKey               string `protobuf:"bytes,2,opt,name=apiKey,proto3" json:"apiKey,omitempty"`
	MatchHistoryAuthCode string `protobuf:"bytes,3,opt,name=matchHistoryAuthCode,proto3" json:"matchHistoryAuthCode,omitempty"`
	PreviousShareCode    string `protobuf:"bytes,4,opt,name=previousShareCode,proto3" json:"previousShareCode,omitempty"`
}

func (x *ShareCodeRequest) Reset() {
	*x = ShareCodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_valveapi_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShareCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareCodeRequest) ProtoMessage() {}

func (x *ShareCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_valveapi_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareCodeRequest.ProtoReflect.Descriptor instead.
func (*ShareCodeRequest) Descriptor() ([]byte, []int) {
	return file_proto_valveapi_proto_rawDescGZIP(), []int{1}
}

func (x *ShareCodeRequest) GetSteamId() uint64 {
	if x != nil {
		return x.SteamId
	}
	return 0
}

func (x *ShareCodeRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *ShareCodeRequest) GetMatchHistoryAuthCode() string {
	if x != nil {
		return x.MatchHistoryAuthCode
	}
	return ""
}

func (x *ShareCodeRequest) GetPreviousShareCode() string {
	if x != nil {
		return x.PreviousShareCode
	}
	return ""
}

var File_proto_valveapi_proto protoreflect.FileDescriptor

var file_proto_valveapi_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x61, 0x6c, 0x76, 0x65, 0x61, 0x70, 0x69,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x76, 0x61, 0x6c, 0x76, 0x65, 0x61, 0x70, 0x69,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x22, 0x73, 0x0a, 0x09, 0x53, 0x68, 0x61, 0x72, 0x65, 0x43,
	0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x64, 0x12, 0x1c, 0x0a,
	0x09, 0x6f, 0x75, 0x74, 0x63, 0x6f, 0x6d, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x09, 0x6f, 0x75, 0x74, 0x63, 0x6f, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x61, 0x74, 0x63, 0x68, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x6d, 0x61,
	0x74, 0x63, 0x68, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0xa6, 0x01, 0x0a, 0x10,
	0x53, 0x68, 0x61, 0x72, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x18, 0x0a, 0x07, 0x73, 0x74, 0x65, 0x61, 0x6d, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x07, 0x73, 0x74, 0x65, 0x61, 0x6d, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x70,
	0x69, 0x4b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x70, 0x69, 0x4b,
	0x65, 0x79, 0x12, 0x32, 0x0a, 0x14, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x48, 0x69, 0x73, 0x74, 0x6f,
	0x72, 0x79, 0x41, 0x75, 0x74, 0x68, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x14, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x41, 0x75,
	0x74, 0x68, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x2c, 0x0a, 0x11, 0x70, 0x72, 0x65, 0x76, 0x69, 0x6f,
	0x75, 0x73, 0x53, 0x68, 0x61, 0x72, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x11, 0x70, 0x72, 0x65, 0x76, 0x69, 0x6f, 0x75, 0x73, 0x53, 0x68, 0x61, 0x72, 0x65,
	0x43, 0x6f, 0x64, 0x65, 0x32, 0x69, 0x0a, 0x14, 0x56, 0x61, 0x6c, 0x76, 0x65, 0x4d, 0x61, 0x74,
	0x63, 0x68, 0x41, 0x70, 0x69, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x51, 0x0a, 0x10,
	0x47, 0x65, 0x74, 0x4e, 0x65, 0x78, 0x74, 0x53, 0x68, 0x61, 0x72, 0x65, 0x43, 0x6f, 0x64, 0x65,
	0x12, 0x20, 0x2e, 0x76, 0x61, 0x6c, 0x76, 0x65, 0x61, 0x70, 0x69, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x2e, 0x53, 0x68, 0x61, 0x72, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x19, 0x2e, 0x76, 0x61, 0x6c, 0x76, 0x65, 0x61, 0x70, 0x69, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x2e, 0x53, 0x68, 0x61, 0x72, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x00, 0x42,
	0x18, 0x5a, 0x16, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x76, 0x61, 0x6c, 0x76, 0x65,
	0x61, 0x70, 0x69, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_proto_valveapi_proto_rawDescOnce sync.Once
	file_proto_valveapi_proto_rawDescData = file_proto_valveapi_proto_rawDesc
)

func file_proto_valveapi_proto_rawDescGZIP() []byte {
	file_proto_valveapi_proto_rawDescOnce.Do(func() {
		file_proto_valveapi_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_valveapi_proto_rawDescData)
	})
	return file_proto_valveapi_proto_rawDescData
}

var file_proto_valveapi_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_valveapi_proto_goTypes = []interface{}{
	(*ShareCode)(nil),        // 0: valveapiclient.ShareCode
	(*ShareCodeRequest)(nil), // 1: valveapiclient.ShareCodeRequest
}
var file_proto_valveapi_proto_depIdxs = []int32{
	1, // 0: valveapiclient.ValveMatchApiService.GetNextShareCode:input_type -> valveapiclient.ShareCodeRequest
	0, // 1: valveapiclient.ValveMatchApiService.GetNextShareCode:output_type -> valveapiclient.ShareCode
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_valveapi_proto_init() }
func file_proto_valveapi_proto_init() {
	if File_proto_valveapi_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_valveapi_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShareCode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_valveapi_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShareCodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_valveapi_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_valveapi_proto_goTypes,
		DependencyIndexes: file_proto_valveapi_proto_depIdxs,
		MessageInfos:      file_proto_valveapi_proto_msgTypes,
	}.Build()
	File_proto_valveapi_proto = out.File
	file_proto_valveapi_proto_rawDesc = nil
	file_proto_valveapi_proto_goTypes = nil
	file_proto_valveapi_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ValveMatchApiServiceClient is the client API for ValveMatchApiService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ValveMatchApiServiceClient interface {
	GetNextShareCode(ctx context.Context, in *ShareCodeRequest, opts ...grpc.CallOption) (*ShareCode, error)
}

type valveMatchApiServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewValveMatchApiServiceClient(cc grpc.ClientConnInterface) ValveMatchApiServiceClient {
	return &valveMatchApiServiceClient{cc}
}

func (c *valveMatchApiServiceClient) GetNextShareCode(ctx context.Context, in *ShareCodeRequest, opts ...grpc.CallOption) (*ShareCode, error) {
	out := new(ShareCode)
	err := c.cc.Invoke(ctx, "/valveapiclient.ValveMatchApiService/GetNextShareCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ValveMatchApiServiceServer is the server API for ValveMatchApiService service.
type ValveMatchApiServiceServer interface {
	GetNextShareCode(context.Context, *ShareCodeRequest) (*ShareCode, error)
}

// UnimplementedValveMatchApiServiceServer can be embedded to have forward compatible implementations.
type UnimplementedValveMatchApiServiceServer struct {
}

func (*UnimplementedValveMatchApiServiceServer) GetNextShareCode(context.Context, *ShareCodeRequest) (*ShareCode, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNextShareCode not implemented")
}

func RegisterValveMatchApiServiceServer(s *grpc.Server, srv ValveMatchApiServiceServer) {
	s.RegisterService(&_ValveMatchApiService_serviceDesc, srv)
}

func _ValveMatchApiService_GetNextShareCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShareCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ValveMatchApiServiceServer).GetNextShareCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/valveapiclient.ValveMatchApiService/GetNextShareCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ValveMatchApiServiceServer).GetNextShareCode(ctx, req.(*ShareCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ValveMatchApiService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "valveapiclient.ValveMatchApiService",
	HandlerType: (*ValveMatchApiServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNextShareCode",
			Handler:    _ValveMatchApiService_GetNextShareCode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/valveapi.proto",
}
